#!/bin/sh

NAME=squeezelite
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
# Read: squeezelite -?
DAEMON_ARGS="-n SqueezeliteNanoPiNEO -o hw:0,0"

# Sanity checks
test -f $DAEMON || exit 0

start() {
        printf "Starting $NAME: "
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
		--make-pidfile --background -- $DAEMON_ARGS \
                && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping $NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
