#!/bin/sh

DAEMON=/opt/RoonBridge/start.sh
PIDFILE=/var/run/roonbridge.pid

# Sanity checks
test -f $DAEMON || exit 0

start() {
        printf "Starting RoonBridge: "
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
                --make-pidfile --background \
                && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping RoonBridge: "
        start-stop-daemon --stop --quiet --exec /opt/RoonBridge/RoonMono/bin/mono-sgen \
                && echo "OK" || echo "FAIL"
	rm $PIDFILE
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
