#!/bin/sh

NAME=Spotifyd
DAEMON=/opt/spotifyd-arm64

# Sanity checks
test -f $DAEMON || exit 0

start() {
        printf "Starting $NAME: "
        start-stop-daemon --start --quiet --background --exec $DAEMON \
                && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping $NAME: "
        start-stop-daemon --stop --quiet --exec $DAEMON \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
